dorm/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'^login.html$', views.user_login, name='user_login'),
    url(r'^confirm.html$', views.confirm, name='confirm'),

    url(r'^housemaster/$', views.housemaster__index, name='housemaster__index'),
    url(r'^housemaster/add_visitor.html$', views.housemaster__add_visitor, name='housemaster__add_visitor'),
    url(r'^housemaster/new_visitor.html$', views.housemaster__new_visitor, name='housemaster__new_visitor'),
    url(r'^housemaster/building.html$', views.housemaster__building, name='housemaster__building'),
    url(r'^housemaster/checkin.html$', views.housemaster__checkin, name='housemaster__checkin'),
    url(r'^housemaster/checkin_result.html$', views.housemaster__checkin_result, name='housemaster__checkin_result'),
    url(r'^housemaster/index.html$', views.housemaster__index, name='housemaster__index'),
    url(r'^housemaster/lookup.html$', views.housemaster__lookup, name='housemaster__lookup'),
    url(r'^housemaster/lookup_result.html$', views.housemaster__lookup_result, name='housemaster__lookup_result'),
    url(r'^housemaster/(?P<roomid>.*)/member.html$', views.housemaster__member, name='housemaster__member'),
    url(r'^housemaster/unsubscribe.html$', views.housemaster__unsubscribe, name='housemaster__unsubscribe'),
    url(r'^housemaster/unsubscribe_result.html$', views.housemaster__unsubscribe_result, name='housemaster__unsubscribe_result'),
    url(r'^housemaster/visitor.html$', views.housemaster__visitor, name='housemaster__visitor'),
    url(r'^housemaster/mark.html$', views.housemaster__mark, name='housemaster__mark'),
    url(r'^housemaster/new_mark.html$', views.housemaster__new_mark, name='housemaster__new_mark'),

    url(r'^instructor/$', views.instructor__index, name='instructor__index'),
    url(r'^instructor/checkin.html$', views.instructor__checkin, name='instructor__checkin'),
    url(r'^instructor/checkin_result.html$', views.instructor__checkin_result, name='instructor__checkin_result'),
    url(r'^instructor/(?P<classid>.*)/class.html$', views.instructor__class, name='instructor__class'),
    url(r'^instructor/index.html$', views.instructor__index, name='instructor__index'),
    url(r'^instructor/lookup.html$', views.instructor__lookup, name='instructor__lookup'),
    url(r'^instructor/lookup_result.html$', views.instructor__lookup_result, name='instructor__lookup_result'),
    url(r'^instructor/(?P<sno>.*)/member.html$', views.instructor__member, name='instructor__member'),
    url(r'^instructor/unsubscribe.html$', views.instructor__unsubscribe, name='instructor__unsubscribe'),
    url(r'^instructor/unsubscribe_result.html$', views.instructor__unsubscribe_result, name='instructor__unsubscribe_result'),

    url(r'^maintenance/$', views.maintenance__index, name='maintenance__index'),
    url(r'^maintenance/index.html$', views.maintenance__index, name='maintenance__index'),
    url(r'^maintenance/(?P<repairid>.*)/repair.html$', views.maintenance__repair, name='maintenance__repair'),
    url(r'^maintenance/(?P<repairid>.*)/repair_result.html$', views.maintenance__repair_result, name='maintenance__repair_result'),

    url(r'^secretary/$', views.secretary__index, name='secretary__index'),
    url(r'^secretary/building.html$', views.secretary__building, name='secretary__building'),
    url(r'^secretary/checkin.html$', views.secretary__checkin, name='secretary__checkin'),
    url(r'^secretary/checkin_result.html$', views.secretary__checkin_result, name='secretary__checkin_result'),
    url(r'^secretary/(?P<classid>.*)/class.html$', views.secretary__class, name='secretary__class'),
    url(r'^secretary/index.html$', views.secretary__index, name='secretary__index'),
    url(r'^secretary/lookup.html$', views.secretary__lookup, name='secretary__lookup'),
    url(r'^secretary/lookup_result.html$', views.secretary__lookup_result, name='secretary__lookup_result'),
    url(r'^secretary/(?P<sno>.*)/member.html$', views.secretary__member, name='secretary__member'),
    url(r'^secretary/unsubscribe.html$', views.secretary__unsubscribe, name='secretary__unsubscribe'),
    url(r'^secretary/unsubscribe_result.html$', views.secretary__unsubscribe_result, name='secretary__unsubscribe_result'),

    url(r'^student/$', views.student__index, name='student__index'),
    url(r'^student/(?P<roomid>.*)/checkin.html$', views.student__checkin, name='student__checkin'),
    url(r'^student/(?P<buildingid>.*)/building.html$', views.student__building, name='student__building'),
    url(r'^student/building_select.html$', views.student__building_select, name='student__building_select'),
    url(r'^student/fee.html$', views.student__fee, name='student__fee'),
    url(r'^student/index.html$', views.student__index, name='student__index'),
    url(r'^student/mark.html$', views.student__mark, name='student__mark'),
    url(r'^student/repair.html$', views.student__repair, name='student__repair'),
    url(r'^student/new_repair.html$', views.student__new_repair, name='student__new_repair'),
    url(r'^student/repair_record.html$', views.student__repair_record, name='student__repair_record'),
    url(r'^student/unsubscribe.html$', views.student__unsubscribe, name='student__unsubscribe'),
    url(r'^student/unsubscribe_result.html$', views.student__unsubscribe_result, name='student__unsubscribe_result'),
]

dormitory/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^dorm/', include('dorm.urls', namespace='dorm')),
]

dorm/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import User
class Owner(models.Model):
    user = models.OneToOneField(User)
    user_type = models.CharField(max_length=20, null=True)
    def __str__(self):
        return self.user.username

class College(models.Model):
    name = models.CharField(max_length=20)
    def __str__(self):
        return self.name

class Secretary(models.Model):
    user = models.ForeignKey(Owner)
    name = models.CharField(max_length=20)
    contact = models.CharField(max_length=200, null=True)
    collegeid = models.ForeignKey(College)
    def __str__(self):
        return self.name

class Instructor(models.Model):
    user = models.ForeignKey(Owner)
    name = models.CharField(max_length=20)
    contact = models.CharField(max_length=200, null=True)
    def __str__(self):
        return self.name

class Class(models.Model):
    name = models.CharField(max_length=20)
    instructorid = models.ForeignKey(Instructor, null=True)
    collegeid = models.ForeignKey(College, null=True)
    def __str__(self):
        return self.name

class Building(models.Model):
    name = models.CharField(max_length=20)
    amount = models.IntegerField(default=0, null=True)
    def __str__(self):
        return self.name

class Housemaster(models.Model):
    user = models.ForeignKey(Owner)
    name = models.CharField(max_length=20)
    contact = models.CharField(max_length=200, null=True)
    buildingid = models.ForeignKey(Building, null=True)
    def __str__(self):
        return self.name

class Visitor(models.Model):
    name = models.CharField(max_length=20)
    sex = models.BooleanField()
    document_type = models.CharField(max_length=20, null=True)
    documentno = models.CharField(max_length=20, null=True)
    contact = models.CharField(max_length=200, null=True)
    dt = models.DateTimeField()
    housemasterid = models.ForeignKey(Housemaster)
    def __str__(self):
        return self.name

class Room(models.Model):
    name = models.CharField(max_length=20)
    room_type = models.CharField(max_length=20, null=True)
    capacity = models.IntegerField(default=0, null=True)
    buildingid = models.ForeignKey(Building)
    def __str__(self):
        return self.name

class Mark(models.Model):
    roomid = models.ForeignKey(Room)
    dt = models.DateTimeField()
    score = models.FloatField()
    housemasterid = models.ForeignKey(Housemaster)
    remark = models.TextField(null=True)
    class Meta:
        unique_together = ('roomid', 'dt')

class Fee(models.Model):
    roomid = models.OneToOneField(Room, primary_key=True)
    remain = models.FloatField()

class FeeRecord(models.Model):
    roomid = models.ForeignKey(Room)
    dt = models.DateTimeField()
    amount = models.FloatField()
    class Meta:
        unique_together = ('roomid', 'dt')

class Student(models.Model):
    sno = models.CharField(max_length=20, primary_key=True)
    user = models.ForeignKey(Owner)
    name = models.CharField(max_length=20)
    sex = models.NullBooleanField(null=True)
    classid = models.ForeignKey(Class, null=True)
    roomid = models.ForeignKey(Room, null=True)
    contact = models.CharField(max_length=200, null=True)
    def __str__(self):
        return self.name

class EnterApply(models.Model):
    sno = models.ForeignKey(Student)
    roomid = models.ForeignKey(Room)
    dt = models.DateTimeField()
    housemaster_check = models.NullBooleanField(null=True)
    instructor_check = models.NullBooleanField(null=True)
    secretary_check = models.NullBooleanField(null=True)
    class Meta:
        unique_together = ('sno', 'roomid', 'dt')

class QuitApply(models.Model):
    sno = models.ForeignKey(Student)
    roomid = models.ForeignKey(Room)
    dt = models.DateTimeField()
    reason = models.TextField()
    housemaster_check = models.NullBooleanField(null=True)
    instructor_check = models.NullBooleanField(null=True)
    secretary_check = models.NullBooleanField(null=True)
    class Meta:
        unique_together = ('sno', 'roomid', 'dt')

class LiveRecord(models.Model):
    sno = models.ForeignKey(Student)
    roomid = models.ForeignKey(Room)
    enter_time = models.DateTimeField()
    quit_time = models.DateTimeField(null=True)
    class Meta:
        unique_together = ('sno', 'roomid', 'enter_time')

class Maintenance(models.Model):
    user = models.ForeignKey(Owner)
    name = models.CharField(max_length=20)
    contact = models.CharField(max_length=200, null=True)
    def __str__(self):
        return self.name

class Repair(models.Model):
    item = models.CharField(max_length=20)
    roomid = models.ForeignKey(Room)
    book_dt = models.DateTimeField()
    reason = models.TextField(null=True)
    fix_dt = models.DateTimeField(null=True)
    maintenanceid = models.ForeignKey(Maintenance, null=True)
    remark = models.TextField(null=True)
    class Meta:
        unique_together = ('item', 'roomid', 'book_dt')
    def __str__(self):
        return self.item

dorm/templates/dorm/instructor/checkin.html
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    </head>
    <body bgcolor="lightblue" >
        <form action="{% url 'dorm:instructor__checkin_result' %}" method="post" >
            {% csrf_token %}
            <table border="1" >
                <caption>入住申请表</caption>
                <tr><th>学号</th><th>姓名</th><th>房间号</th><th>已住情况</th><th>申请时间</th><th>审核</th></tr>
                {% for rec in rec_set %}
                <tr><td>{{ rec.sno.sno }}</td><td>{{ rec.sno.name }}</td><td>{{ rec.roomid.name }}</td><td>{{ rec.occupant }}/{{ rec.roomid.capacity }}</td><td>{{ rec.dt }}</td><td><input type="checkbox" name="checked" value="{{ rec.id }}" {% if rec.instructor_check %}checked{% endif %} /></td></tr>
                {% endfor %}
            </table>
            <input type="submit" value="提交" />
        </form>
        <a href="{% url 'dorm:instructor__index' %}" >返回</a>
    </body>
</html>

dorm/templates/dorm/instructor/class.html
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    </head>
    <body bgcolor="lightblue" >
        <p>{{ cls.name }}班共有{{ student_amount }}位学生，分布在{{ building_amount }}个楼栋{{ room_amount }}间宿舍里</p>
        <table border="1">
            <tr><th>学号</th><th>姓名</th><th>性别</th><th>联系方式</th><th>楼栋名</th><th>房间名</th><th>房间类别</th><th>操作</th></tr>
            {% for student in student_set %}
            <tr><td>{{ student.sno }}</td><td>{{ student.name }}</td><td>{% if student.sex %}男{% else %}女{% endif %}</td><td>{{ student.contact }}</td><td>{{ student.roomid.buildingid.name }}</td><td>{{ student.roomid.name }}</td><td>{{ student.roomid.room_type }}</td><td><a href="{% url 'dorm:instructor__member' student.sno %}">查看寝室成员</a></td></tr>
            {% endfor %}
        </table>
        <a href="{% url 'dorm:instructor__index' %}" >返回</a><br />
    </body>
</html>

dorm/templates/dorm/instructor/index.html
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    </head>
    <body bgcolor="lightblue" >
        <p>{{ instructor.name }}辅导员，你好</p>
        {% for cls in class_set %}
        <a href="{% url 'dorm:instructor__class' cls.id %}" >{{ cls.name }}</a><br />
        {% endfor %}
        <a href="{% url 'dorm:instructor__lookup' %}" >查询学生信息</a><br />
        <a href="{% url 'dorm:instructor__checkin' %}" >入住审核</a><br />
        <a href="{% url 'dorm:instructor__unsubscribe' %}" >退宿审核</a><br />
        <a href="{% url 'dorm:user_login' %}" >注销</a><br />
    </body>
</html>

dorm/templates/dorm/instructor/lookup.html
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    </head>
    <body bgcolor="lightblue" >
        <form action="{% url 'dorm:instructor__lookup_result' %}" method="post" >
            {% csrf_token %}
            <label for="name" >姓名：</label><input id="name" type="text" name="name" /><br />
            <input type="submit" value="查询" /><br />
        </form>
        <a href="{% url 'dorm:instructor__index' %}" >返回</a>
    </body>
</html>

dorm/templates/dorm/instructor/lookup_result.html
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    </head>
    <body bgcolor="lightblue" >
        <table border="1">
            <caption>符合条件的学生记录</caption>
            <tr><th>学号</th><th>姓名</th><th>班级</th><th>楼栋</th><th>房间</th><th>性别</th><th>联系方式</th><th>辅导员</th><th>辅导员联系方式</th></tr>
            {% for student in student_set %}
            <tr><td>{{ student.sno }}</td><td>{{ student.name }}</td><td>{{ student.classid.name }}</td><td>{{ student.roomid.buildingid.name }}</td><td>{{ student.roomid.name }}</td><td>{% if student.sex == True %}男{% else %}女{% endif %}</td><td>{{ student.contact }}</td><td>{{ student.classid.instructorid.name }}</td><td>{{ student.classid.instructorid.contact }}</td></tr>
            {% endfor %}
        </table>
        <a href="{% url 'dorm:instructor__lookup' %}" >返回</a>
    </body>
</html>

dorm/templates/dorm/instructor/member.html
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    </head>
    <body bgcolor="lightblue" >
        <table border="1">
            <caption><strong>{{ room.buildingid.name }}</strong>栋<strong>{{ room.name }}</strong>成员</caption>
            <tr><th>学号</th><th>姓名</th><th>班级</th><th>性别</th><th>联系方式</th><th>辅导员</th><th>辅导员联系方式</th></tr>
            {% for student in student_set %}
            <tr><td>{{ student.sno }}</td><td>{{ student.name }}</td><td>{{ student.classid.name }}</td><td>{% if student.sex %}男{% else %}女{% endif %}</td><td>{{ student.contact }}</td><td>{{ student.classid.instructorid.name }}</td><td>{{ student.classid.instructorid.contact }}</td></tr>
            {% endfor %}
        </table>
        <a href="{% url 'dorm:instructor__class' classid %}" >返回</a>
    </body>
</html>

dorm/templates/dorm/instructor/unsubscribe.html
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    </head>
    <body bgcolor="lightblue" >
        <form action="{% url 'dorm:instructor__unsubscribe_result' %}" method="post" >
            {% csrf_token %}
            <table border="1" >
                <caption>退宿申请表</caption>
                <tr><th>学号</th><th>姓名</th><th>房间号</th><th>已住情况</th><th>申请时间</th><th>申请原因</th><th>审核</th></tr>
                {% for rec in rec_set %}
                <tr><td>{{ rec.sno.sno }}</td><td>{{ rec.sno.name }}</td><td>{{ rec.roomid.name }}</td><td>{{ rec.occupant }}/{{ rec.roomid.capacity }}</td><td>{{ rec.dt }}</td><td>{{ rec.reason }}</td><td><input type="checkbox" name="checked" value="{{ rec.id }}" {% if rec.instructor_check %}checked{% endif %} /></td></tr>
                {% endfor %}
            </table>
            <input type="submit" value="提交" />
        </form>
        <a href="{% url 'dorm:instructor__index' %}" >返回</a>
    </body>
</html>