dorm/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'^login.html$', views.user_login, name='user_login'),
    url(r'^confirm.html$', views.confirm, name='confirm'),

    url(r'^housemaster/$', views.housemaster__index, name='housemaster__index'),
    url(r'^housemaster/add_visitor.html$', views.housemaster__add_visitor, name='housemaster__add_visitor'),
    url(r'^housemaster/new_visitor.html$', views.housemaster__new_visitor, name='housemaster__new_visitor'),
    url(r'^housemaster/building.html$', views.housemaster__building, name='housemaster__building'),
    url(r'^housemaster/checkin.html$', views.housemaster__checkin, name='housemaster__checkin'),
    url(r'^housemaster/checkin_result.html$', views.housemaster__checkin_result, name='housemaster__checkin_result'),
    url(r'^housemaster/index.html$', views.housemaster__index, name='housemaster__index'),
    url(r'^housemaster/lookup.html$', views.housemaster__lookup, name='housemaster__lookup'),
    url(r'^housemaster/lookup_result.html$', views.housemaster__lookup_result, name='housemaster__lookup_result'),
    url(r'^housemaster/(?P<roomid>.*)/member.html$', views.housemaster__member, name='housemaster__member'),
    url(r'^housemaster/unsubscribe.html$', views.housemaster__unsubscribe, name='housemaster__unsubscribe'),
    url(r'^housemaster/unsubscribe_result.html$', views.housemaster__unsubscribe_result, name='housemaster__unsubscribe_result'),
    url(r'^housemaster/visitor.html$', views.housemaster__visitor, name='housemaster__visitor'),
    url(r'^housemaster/mark.html$', views.housemaster__mark, name='housemaster__mark'),
    url(r'^housemaster/new_mark.html$', views.housemaster__new_mark, name='housemaster__new_mark'),

    url(r'^instructor/$', views.instructor__index, name='instructor__index'),
    url(r'^instructor/checkin.html$', views.instructor__checkin, name='instructor__checkin'),
    url(r'^instructor/checkin_result.html$', views.instructor__checkin_result, name='instructor__checkin_result'),
    url(r'^instructor/(?P<classid>.*)/class.html$', views.instructor__class, name='instructor__class'),
    url(r'^instructor/index.html$', views.instructor__index, name='instructor__index'),
    url(r'^instructor/lookup.html$', views.instructor__lookup, name='instructor__lookup'),
    url(r'^instructor/lookup_result.html$', views.instructor__lookup_result, name='instructor__lookup_result'),
    url(r'^instructor/(?P<sno>.*)/member.html$', views.instructor__member, name='instructor__member'),
    url(r'^instructor/unsubscribe.html$', views.instructor__unsubscribe, name='instructor__unsubscribe'),
    url(r'^instructor/unsubscribe_result.html$', views.instructor__unsubscribe_result, name='instructor__unsubscribe_result'),

    url(r'^maintenance/$', views.maintenance__index, name='maintenance__index'),
    url(r'^maintenance/index.html$', views.maintenance__index, name='maintenance__index'),
    url(r'^maintenance/(?P<repairid>.*)/repair.html$', views.maintenance__repair, name='maintenance__repair'),
    url(r'^maintenance/(?P<repairid>.*)/repair_result.html$', views.maintenance__repair_result, name='maintenance__repair_result'),

    url(r'^secretary/$', views.secretary__index, name='secretary__index'),
    url(r'^secretary/building.html$', views.secretary__building, name='secretary__building'),
    url(r'^secretary/checkin.html$', views.secretary__checkin, name='secretary__checkin'),
    url(r'^secretary/checkin_result.html$', views.secretary__checkin_result, name='secretary__checkin_result'),
    url(r'^secretary/(?P<classid>.*)/class.html$', views.secretary__class, name='secretary__class'),
    url(r'^secretary/index.html$', views.secretary__index, name='secretary__index'),
    url(r'^secretary/lookup.html$', views.secretary__lookup, name='secretary__lookup'),
    url(r'^secretary/lookup_result.html$', views.secretary__lookup_result, name='secretary__lookup_result'),
    url(r'^secretary/(?P<sno>.*)/member.html$', views.secretary__member, name='secretary__member'),
    url(r'^secretary/unsubscribe.html$', views.secretary__unsubscribe, name='secretary__unsubscribe'),
    url(r'^secretary/unsubscribe_result.html$', views.secretary__unsubscribe_result, name='secretary__unsubscribe_result'),

    url(r'^student/$', views.student__index, name='student__index'),
    url(r'^student/(?P<roomid>.*)/checkin.html$', views.student__checkin, name='student__checkin'),
    url(r'^student/(?P<buildingid>.*)/building.html$', views.student__building, name='student__building'),
    url(r'^student/building_select.html$', views.student__building_select, name='student__building_select'),
    url(r'^student/fee.html$', views.student__fee, name='student__fee'),
    url(r'^student/index.html$', views.student__index, name='student__index'),
    url(r'^student/mark.html$', views.student__mark, name='student__mark'),
    url(r'^student/repair.html$', views.student__repair, name='student__repair'),
    url(r'^student/new_repair.html$', views.student__new_repair, name='student__new_repair'),
    url(r'^student/repair_record.html$', views.student__repair_record, name='student__repair_record'),
    url(r'^student/unsubscribe.html$', views.student__unsubscribe, name='student__unsubscribe'),
    url(r'^student/unsubscribe_result.html$', views.student__unsubscribe_result, name='student__unsubscribe_result'),
]

dormitory/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^dorm/', include('dorm.urls', namespace='dorm')),
]

dorm/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import User
class Owner(models.Model):
    user = models.OneToOneField(User)
    user_type = models.CharField(max_length=20, null=True)
    def __str__(self):
        return self.user.username

class College(models.Model):
    name = models.CharField(max_length=20)
    def __str__(self):
        return self.name

class Secretary(models.Model):
    user = models.ForeignKey(Owner)
    name = models.CharField(max_length=20)
    contact = models.CharField(max_length=200, null=True)
    collegeid = models.ForeignKey(College)
    def __str__(self):
        return self.name

class Instructor(models.Model):
    user = models.ForeignKey(Owner)
    name = models.CharField(max_length=20)
    contact = models.CharField(max_length=200, null=True)
    def __str__(self):
        return self.name

class Class(models.Model):
    name = models.CharField(max_length=20)
    instructorid = models.ForeignKey(Instructor, null=True)
    collegeid = models.ForeignKey(College, null=True)
    def __str__(self):
        return self.name

class Building(models.Model):
    name = models.CharField(max_length=20)
    amount = models.IntegerField(default=0, null=True)
    def __str__(self):
        return self.name

class Housemaster(models.Model):
    user = models.ForeignKey(Owner)
    name = models.CharField(max_length=20)
    contact = models.CharField(max_length=200, null=True)
    buildingid = models.ForeignKey(Building, null=True)
    def __str__(self):
        return self.name

class Visitor(models.Model):
    name = models.CharField(max_length=20)
    sex = models.BooleanField()
    document_type = models.CharField(max_length=20, null=True)
    documentno = models.CharField(max_length=20, null=True)
    contact = models.CharField(max_length=200, null=True)
    dt = models.DateTimeField()
    housemasterid = models.ForeignKey(Housemaster)
    def __str__(self):
        return self.name

class Room(models.Model):
    name = models.CharField(max_length=20)
    room_type = models.CharField(max_length=20, null=True)
    capacity = models.IntegerField(default=0, null=True)
    buildingid = models.ForeignKey(Building)
    def __str__(self):
        return self.name

class Mark(models.Model):
    roomid = models.ForeignKey(Room)
    dt = models.DateTimeField()
    score = models.FloatField()
    housemasterid = models.ForeignKey(Housemaster)
    remark = models.TextField(null=True)
    class Meta:
        unique_together = ('roomid', 'dt')

class Fee(models.Model):
    roomid = models.OneToOneField(Room, primary_key=True)
    remain = models.FloatField()

class FeeRecord(models.Model):
    roomid = models.ForeignKey(Room)
    dt = models.DateTimeField()
    amount = models.FloatField()
    class Meta:
        unique_together = ('roomid', 'dt')

class Student(models.Model):
    sno = models.CharField(max_length=20, primary_key=True)
    user = models.ForeignKey(Owner)
    name = models.CharField(max_length=20)
    sex = models.NullBooleanField(null=True)
    classid = models.ForeignKey(Class, null=True)
    roomid = models.ForeignKey(Room, null=True)
    contact = models.CharField(max_length=200, null=True)
    def __str__(self):
        return self.name

class EnterApply(models.Model):
    sno = models.ForeignKey(Student)
    roomid = models.ForeignKey(Room)
    dt = models.DateTimeField()
    housemaster_check = models.NullBooleanField(null=True)
    instructor_check = models.NullBooleanField(null=True)
    secretary_check = models.NullBooleanField(null=True)
    class Meta:
        unique_together = ('sno', 'roomid', 'dt')

class QuitApply(models.Model):
    sno = models.ForeignKey(Student)
    roomid = models.ForeignKey(Room)
    dt = models.DateTimeField()
    reason = models.TextField()
    housemaster_check = models.NullBooleanField(null=True)
    instructor_check = models.NullBooleanField(null=True)
    secretary_check = models.NullBooleanField(null=True)
    class Meta:
        unique_together = ('sno', 'roomid', 'dt')

class LiveRecord(models.Model):
    sno = models.ForeignKey(Student)
    roomid = models.ForeignKey(Room)
    enter_time = models.DateTimeField()
    quit_time = models.DateTimeField(null=True)
    class Meta:
        unique_together = ('sno', 'roomid', 'enter_time')

class Maintenance(models.Model):
    user = models.ForeignKey(Owner)
    name = models.CharField(max_length=20)
    contact = models.CharField(max_length=200, null=True)
    def __str__(self):
        return self.name

class Repair(models.Model):
    item = models.CharField(max_length=20)
    roomid = models.ForeignKey(Room)
    book_dt = models.DateTimeField()
    reason = models.TextField(null=True)
    fix_dt = models.DateTimeField(null=True)
    maintenanceid = models.ForeignKey(Maintenance, null=True)
    remark = models.TextField(null=True)
    class Meta:
        unique_together = ('item', 'roomid', 'book_dt')
    def __str__(self):
        return self.item

dorm/templates/dorm/student/building.html
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    </head>
    <body bgcolor="lightblue" >
        <p><strong>{{ building.name }}</strong>栋详细信息：</p>
        <table border="1">
            <caption>宿管</caption>
            <tr><th>姓名</th><th>联系方式</th></tr>
            {% for housemaster in housemaster_set %}
            <tr><td>{{ housemaster.name }}</td><td>{{ housemaster.contact }}</td></tr>
            {% endfor %}
        </table>
        <p> 共有<strong>{{ building.amount }}</strong>个房间，其中有<strong>{{ empty }}</strong>间空房，<strong>{{ full }}</strong>间全满，<strong>{{ not_full }}</strong>间未满</p>
        <table border="1">
            <tr><th>房间名</th><th>房间类别</th><th>入住情况</th><th>所属班级</th><th>状态</th><th>操作</th></tr>
            {% for room in room_tab %}
            <tr><td>{{ room.name }}</td><td>{{ room.room_type }}</td><td>{{ room.occupant }}/{{ room.capacity }}</td><td>{% for cls in room.class_set %}{{ cls.name }}，{% endfor %}</td><td>{% if room.is_full %}已满{% else %}未满{% endif %}</td><td>{% if room.is_full %}无{% else %}<a href="{% url 'dorm:student__checkin' room.id %}" >申请入住</a>{% endif %}</td></tr>
            {% endfor %}
        </table>
        <a href="{% url 'dorm:student__building_select' %}" >返回</a>
    </body>
</html>

dorm/templates/dorm/student/building_select.html
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    </head>
    <body bgcolor="lightblue" >
        <h3>所有楼栋</h3>
        {% for building in building_set %}
        <a href="{% url 'dorm:student__building' building.id %}" >{{ building.name }}</a><br />
        {% endfor %}
        <a href="{% url 'dorm:student__index' %}" >返回</a>
    </body>
</html>

dorm/templates/dorm/student/fee.html
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    </head>
    <body bgcolor="lightblue" >
        <table border="1">
            <caption><strong>{{ student.roomid.buildingid.name }}</strong>栋<strong>{{ student.roomid.name }}</strong>寝室电费充值记录</caption>
            <tr><th>充值时间</th><th>充值量</th></tr>
            {% for fee_record in fee_record_set %}
            <tr><td>{{ fee_record.dt }}</td><td>{{ fee_record.amount }}</td></tr>
            {% endfor %}
        </table>
        <a href="{% url 'dorm:student__index' %}" >返回</a><br />
    </body>
</html>

dorm/templates/dorm/student/index.html
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    </head>
    <body bgcolor="lightblue" >
        <p><strong>{{ student.name }}</strong>同学，你好</p>
        <p>你的寝室剩余电量为<strong>{{ fee.remain }}</strong>度，{% if fee.remain < 20 %}电量不多了，请尽快充值{% else %}电量充足，请放心使用{% endif %}。</p>
        <p>你的寝室上一次评分在<strong>{{ mark.dt }}</strong>，打分<strong>{{ mark.score }}</strong>分，<strong>{% if mark.score < 60 %}差{% elif mark.score < 75 %}中{% elif mark.score < 90 %}良{% else %}优{% endif %}</strong>，评分人：<strong>{{ mark.housemasterid.name }}</strong>宿管</p>
        <p>你的辅导员是<strong>{{ student.classid.instructorid.name }}</strong>，联系方式：<strong>{{ student.classid.instructorid.contact }}</strong></p>
        <table border="1" >
            <caption><strong>{{ student.classid.collegeid.name }}</strong>书记</caption>
            <tr><th>姓名</th><th>联系方式</th></tr>
            {% for secretary in secretary_set %}
            <tr><td>{{ secretary.name }}</td><td>{{ secretary.contact }}</td></tr>
            {% endfor %}
        </table>
        <table border="1" >
            <caption><strong>{{ student.roomid.buildingid }}</strong>栋宿管</caption>
            <tr><th>姓名</th><th>联系方式</th></tr>
            {% for housemaster in housemaster_set %}
            <tr><td>{{ housemaster.name }}</td><td>{{ housemaster.contact }}</td></tr>
            {% endfor %}
        </table>
        <a href="{% url 'dorm:student__mark' %}" >历史评分</a><br />
        <a href="{% url 'dorm:student__fee' %}" >电费充值记录</a><br />
        <a href="{% url 'dorm:student__unsubscribe' %}" >办理退宿</a><br />
        <a href="{% url 'dorm:student__repair_record' %}" >维修</a><br />
        <a href="{% url 'dorm:student__building_select' %}" >楼栋信息</a><br />
        <a href="{% url 'dorm:user_login' %}" >注销</a><br />
    </body>
</html>

dorm/templates/dorm/student/mark.html
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    </head>
    <body bgcolor="lightblue" >
        <table border="1">
            <caption><strong>{{ student.roomid.buildingid.name }}</strong>栋<strong>{{ student.roomid.name }}</strong>寝室评分记录</caption>
            <tr><th>日期</th><th>评分</th><th>等级</th><th>评分人</th></tr>
            {% for mark in mark_set %}
            <tr><td>{{ mark.dt }}</td><td>{{ mark.score }}</td><td>{% if mark.score < 60 %}差{% elif mark.score < 75 %}中{% elif mark.score < 90 %}良{% else %}优{% endif %}</td><td>{{ mark.housemasterid.name }}</td></tr>
            {% endfor %}
        </table>
        <a href="{% url 'dorm:student__index' %}" >返回</a><br />
    </body>
</html>

dorm/templates/dorm/student/repair.html
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    </head>
    <body bgcolor="lightblue" >
        <form action="{% url 'dorm:student__new_repair' %}" method="post" >
            {% csrf_token %}
            <label for="name" >物品名：</label><input id="name" type="text" name="item" /><br />
            <label for="reason" >维修原因：</label><input id="reason" type="text" name="reason" /><br />
            <input type="submit" value="提交" /><br />
        </form>
        <a href="{% url 'dorm:student__repair_record' %}" >返回</a>
    </body>
</html>

dorm/templates/dorm/student/repair_record.html
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    </head>
    <body bgcolor="lightblue" >
        <table border="1">
            <caption><strong>{{ student.roomid.buildingid.name }}</strong>栋<strong>{{ student.roomid.name }}</strong>寝室维修记录</caption>
            <tr><th>物品名</th><th>登记时间</th><th>维修原因</th><th>维修时间</th><th>维修人员</th><th>维修人员联系方式</th><th>维修人员备注</th></tr>
            {% for repair in repair_set %}
            <tr><td>{{ repair.item }}</td><td>{{ repair.book_dt }}</td><td>{{ repair.reason }}</td><td>{{ repair.fix_dt }}</td><td>{{ repair.maintenanceid.name }}</td><td>{{ repair.maintenanceid.contact }}</td><td>{{ repair.remark }}</td></tr>
            {% endfor %}
        </table>
        <a href="{% url 'dorm:student__repair' %}" >新增维修</a><br />
        <a href="{% url 'dorm:student__index' %}" >返回</a>
    </body>
</html>

dorm/templates/dorm/student/unsubscribe.html
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    </head>
    <body bgcolor="lightblue" >
        <form action="{% url 'dorm:student__unsubscribe_result' %}" method="post" >
            {% csrf_token %}
            <label for="reason" >退宿原因：</label><input id="reason" type="text" name="reason" /><br />
            <input type="submit" value="提交" /><br />
        </form>
        <a href="{% url 'dorm:student__index' %}" >返回</a>
    </body>
</html>